version: "3.7"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  web:
    environment:
      - ENV=LOCAL
      - SECRET_KEY=${SECRET_KEY}
      - FORM_AUTOCOMPLETE_OFF=False
      # - USE_LOCALSTACK=True
    build: .
    command: /code/run.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      # - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "localstack-vol:/tmp/localstack"
  mailhog:
     image: mailhog/mailhog
     ports:
       - 1025:1025 # smtp server
       - 8025:8025 # web ui
     # command: -invite-jim=1 -jim-accept=0.50  # uncomment to enable and configure Jim (Chaos Monkey)
volumes:
  postgres_data:
  localstack-vol:
