version: "3.7"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    environment:
      - ENV=LOCAL
      - SECRET_KEY=${SECRET_KEY}
      - FORM_AUTOCOMPLETE_OFF=False
    build: .
    command: /code/run.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  mailhog:
     image: mailhog/mailhog
     ports:
       - 1025:1025 # smtp server
       - 8025:8025 # web ui
volumes:
  postgres_data:
