# Generated by Django 2.2.17 on 2021-03-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0100_auto_20210310_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='americareport',
            name='final_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
