# Generated by Django 2.2.17 on 2021-03-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cts_forms', '0102_waiveremailreportcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverResponseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('body', models.TextField()),
            ],
        ),
    ]
